# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='企业类型')),
                ('cname', models.CharField(max_length=255, verbose_name='企业名称')),
                ('adress', models.CharField(max_length=255, verbose_name='企业地址')),
                ('name', models.CharField(max_length=20, verbose_name='联系人')),
                ('mobile', models.CharField(max_length=20, verbose_name='电话')),
                ('introduction', models.TextField(max_length=1000, verbose_name='企业介绍')),
                ('service', models.TextField(max_length=1000, verbose_name='产品服务介绍')),
                ('credit', models.TextField(max_length=1000, verbose_name='荣誉与资质')),
                ('financing', models.TextField(max_length=1000, verbose_name='融资情况')),
                ('profit', models.TextField(max_length=1000, verbose_name='营收情况')),
                ('img', models.ImageField(upload_to='upload', verbose_name='企业logo')),
            ],
            options={
                'verbose_name': '调查信息',
                'verbose_name_plural': '调查信息',
            },
        ),
    ]
